spring:
  jpa:
    show-sql: true
    # database: POSTGRESQL
    # hibernate:
    #   ddl-auto: create-drop
  datasource:
    # platform: postgres
    url: jdbc:sqlserver://localhost:1433;encrypt=true;integratedSecurity=false;TrustServerCertificate=true;databaseName=javaapis
    username: sa
    password: s3cr3t
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080 
#debug: true